[package]
name = "contracts"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
contracts = "0x0"
# ObjectID = "0x59823c72b78c56e2a0fb1ac9ae2fbefbfc6cc5a08c48692db1a9268c9d706b6e"
# PackageID = "0x0870f322afea4ff897e855b74d200d14893c701b50678a8a9151ebf2f56d4848"
# DealID = "0x691ada0790da256a0a54c6dda2efdfffd90e0822efeff8ebc5078370c0ec2fb0"

# Create Deal
sui client call --package $PACKAGE_ID --module earnout --function create_deal \
--args "Acquisition Deal 2025" "0xSELLER_ADDRESS" "0xAUDITOR_ADDRESS" \
--gas-budget 10000000

# Actual Create Deal input
sui client call --package $PACKAGE_ID --module earnout --function create_deal \
--args "Acquisition Deal 2025" 0x7cb40464099294706d3596c5c8a0c84ce007bd085981cfae66d0634e359803ef 0x7cb40464099294706d3596c5c8a0c84ce007bd085981cfae66d0634e359803ef \
--gas-budget 10000000

# Add Period
sui client call --package $PACKAGE_ID --module earnout --function add_period \
--args $DEAL_ID "2025-Q1" \
--gas-budget 10000000

# Add Walrus Blob
sui client call --package $PACKAGE_ID --module earnout --function add_walrus_blob \
--args $DEAL_ID 0 "blob_id_example_123" "financial_report" 0x6 \
--gas-budget 10000000