[package]
name = "contracts"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
contracts = "0x0"
# ObjectID = "0x228f84944579efb3df1f5abf7442a8f79eb5611f8b06154115e8de03904a8a37"
# PackageID = "0xb2752ee42f5d063dcda98497df71a79e54d37908bfd8d9e23257cd618f92bce6"
# DealID = "0xf4c0bb98320bbfa208b00e1a2c816588bf49fa7d0b964d4603a8e2ce868cf8b7"

sui client call --package $PACKAGE_ID --module earnout --function create_deal \
--args "Acquisition Deal 2025" 0x7cb40464099294706d3596c5c8a0c84ce007bd085981cfae66d0634e359803ef 0x7cb40464099294706d3596c5c8a0c84ce007bd085981cfae66d0634e359803ef \

sui client call --package $PACKAGE_ID --module earnout --function add_period \
--args $DEAL_ID "2025-Q1" 